### PR TITLE
Pricing update

### PR DESCRIPTION
**Pull request by humitos**
Gold is not related to Advanced plan.

### CODE REVIEW

**Comment by nienn** [comment]
The item is still needed but it's pointing to the wrong plan, probably left behind by a copy/past.
It's meant to read _**"All the features from the `Base` plan"**_ --instead of `Advanced` plan.

**Comment by humitos** [comment]
That makes sense. In that case, would we need the same sentence for Ad-free as well?

**Comment by nienn** [comment]
The Ad-free plan already states that in its text:

Screenshot 2022-02-28 084116

It's in sentence style, instead of the list style the other plans use, to reinforce the idea of being a special case and not a plan in itself.

**Review by agjohnson — APPROVED** [review]

**Comment by agjohnson** [comment]
I've updated with the conversation here.

- 0642b958692a6418e92e9d8fc816698d55d09b04 fixes copy some
- 18e60c1 cleans whitespace

**Review by nienn — APPROVED** [review]
LGTM!

**Pull request merged**
