### PR TITLE
Update newsletter-march-2022.rst

### PR DESCRIPTION
**Pull request by humitos**
----
:books: Documentation preview :books:: https://read-the-docs-site-community--180.com.readthedocs.build/

### CODE REVIEW

**Comment by humitos** [comment]
It used the correct hash, `Download action repository 'readthedocs/actions@v1' (SHA:66ede090bf7af04c2307111db3ec6e832fbd67ec)` but it didn't work as we expected 🤔  cc @ericholscher 

This link https://read-the-docs-site-community--180.com.readthedocs.build/en/180/ should be https://read-the-docs-site-community--180.com.readthedocs.build/

**Comment by ericholscher** [comment]
Yea.. not the right URL 🙃

**Comment by humitos** [comment]
I think I fixed it in https://github.com/readthedocs/actions/pull/19

**Comment by humitos** [comment]
I merged that PR and re-tag everything. It worked! 💪🏼

**Comment by ericholscher** [comment]
@humitos Woot!

**Pull request closed without merging**
