### PR TITLE
Readme updates

### LINKED ISSUE #130: Instructions from README are not valid
I tried following the instructions from the README but,

- the `requirements.txt` file does not exist
- after running `npm run dev` it fails because it does not find `pelican`
- I tried installing all the dependencies from `pyproject.toml`

Finally, it fails with the error:

```
[12:03:25] CRITICAL TemplateNotFound: readthedocs/includes/announcements.html                                                                  __init__.py:566
[nodemon] app crashed - waiting for file changes before starting...
```

I'm not sure where that template comes from.

### PR DESCRIPTION
**Pull request by agjohnson**
Closes #130

### CODE REVIEW

**Comment by humitos** [comment]
Something didn't work to me. Do we need to setup this token `FONTAWESOME_NPM_AUTH_TOKEN`?

```
rtfd/code/site-community  agj/readme-updates ✔                                                                                                       14h50m  ⍉
▶ pipx run poetry install
⚠️  poetry is already on your PATH and installed at /home/humitos/.asdf/installs/python/3.10.2/bin/poetry. Downloading and running anyway.
Installing dependencies from lock file

Package operations: 0 installs, 5 updates, 0 removals

  • Updating docutils (0.18.1 -> 0.19)
  • Updating jinja2 (3.1.2 -> 3.0.3)
  • Updating pelican (4.7.2 -> 4.5.0)
  • Updating markdown (3.3.7 -> 3.1.1)
  • Updating pre-commit (2.19.0 -> 2.16.0)
Time: 0h:00m:11s                                                                                                                                               
(python-3.10.2)
rtfd/code/site-community  agj/readme-updates ✔                                                                                                        14h51m  
▶ npm install
Error: Failed to replace env in config: ${FONTAWESOME_NPM_AUTH_TOKEN}
    at /home/humitos/.asdf/installs/nodejs/14.18.1/lib/node_modules/npm/lib/config/core.js:415:13
    at String.replace (<anonymous>)
    at envReplace (/home/humitos/.asdf/installs/nodejs/14.18.1/lib/node_modules/npm/lib/config/core.js:411:12)
    at parseField (/home/humitos/.asdf/installs/nodejs/14.18.1/lib/node_modules/npm/lib/config/core.js:389:7)
    at /home/humitos/.asdf/installs/nodejs/14.18.1/lib/node_modules/npm/lib/config/core.js:330:24
    at Array.forEach (<anonymous>)
    at Conf.add (/home/humitos/.asdf/installs/nodejs/14.18.1/lib/node_modules/npm/lib/config/core.js:328:23)
    at ConfigChain.addString (/home/humitos/.asdf/installs/nodejs/14.18.1/lib/node_modules/npm/node_modules/config-chain/index.js:244:8)
    at Conf.<anonymous> (/home/humitos/.asdf/installs/nodejs/14.18.1/lib/node_modules/npm/lib/config/core.js:316:10)
    at /home/humitos/.asdf/installs/nodejs/14.18.1/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:123:16
/home/humitos/.asdf/installs/nodejs/14.18.1/lib/node_modules/npm/lib/npm.js:59
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (/home/humitos/.asdf/installs/nodejs/14.18.1/lib/node_modules/npm/lib/npm.js:59:13)
    at process.errorHandler (/home/humitos/.asdf/installs/nodejs/14.18.1/lib/node_modules/npm/lib/utils/error-handler.js:208:32)
    at process.emit (events.js:400:28)
    at process._fatalException (internal/process/execution.js:167:25)
(python-3.10.2)
rtfd/code/site-community  agj/readme-updates ✔                                                                                                       14h51m  ⍉
▶
```

I tried setting it as `""` for testing, but it failed with "Unable to authenticate". So, it seems it's used.

**Comment by agjohnson** [comment]
> Do we need to setup this token FONTAWESOME_NPM_AUTH_TOKEN

Ah yes, I need to note that as well. This is indeed required and already set up in CI.

**Comment by agjohnson** [comment]
Updated. I suppose we could also hard code the app token here, I'm pretty sure it's just used as a license identifier.

**Comment by humitos** [comment]
Do I need to create an account somewhere? Or what's the value that I have to use for the token?

**Comment by agjohnson** [comment]
No, it turns out the token just gets attached to my account, there are no team logins -- it's a bit odd.

I'll share the token in chat for now, but just noted in the directions to ask for the token for now.

Thinking about this a little more, I don't like the requirement of this token for authoring content (when CSS/JS changes aren't required). But, currently everything uses a single process, webpack dev server, and it's really nice. I'd hate to have two separate dev processes, one for CSS+JS+HTML and one for just HTML. If we run into trouble with CSS+JS assets, we can re-evaluate, but for now that will mean we need to distribute this token to author content.

I'll open an issue to track this, though it's slightly related to #129

**Comment by agjohnson** [comment]
Also, note, I'm still pushing up local changes, and so these directions should work up until `npm run build` if you have the token here. You'll get similar/same failures as CI build for now, that's expected.

**Comment by humitos** [comment]
I define the variable with the token you shared with me and I was able to install the dependencies. Now, when running `npm run dev` fails with

```
CRITICAL: readthedocs/includes/announcements.html
[nodemon] app crashed - waiting for file changes before starting...
```

I get the same error when running `npm run build-html`.

**Comment by agjohnson** [comment]
Yup, that's expected.

**Comment by humitos** [comment]
Hrm... The problem is that the site does not render when accessing the URL exposed by the command.

**Comment by agjohnson** [comment]
Yeah, noted above, it's not possible to build the site yet. This is just the Readme changes

**Comment by agjohnson** [comment]
For now, this should be accurate, and we can shape this up more with feedback later.

**Pull request merged**
