### PR TITLE
Update poetry dependencies

### PR DESCRIPTION
**Pull request by humitos**
`build` step on CircleCI fails otherwise.

----
:books: Documentation preview :books:: https://read-the-docs-site-community--186.com.readthedocs.build/

### CODE REVIEW

**Review by agjohnson — APPROVED** [review]
I didn't look into the failure, but updating installed dependencies seems like a good idea either way :+1:

**Comment by humitos** [comment]
Meh, poetry fails and it doesn't tell my why.

**Comment by agjohnson** [comment]
You can remove your local env with `poetry env list` to get the env name, and `poetry env remove [name]`. However, in testing this, I'm not sure what exactly is happening:

```
(site-community) site-community/ humitos/poetry-dependencies* 💀  poetry install
Installing dependencies from lock file

Package operations: 26 installs, 1 update, 0 removals

  • Installing markupsafe (2.1.2)
  • Installing pytz (2022.7.1)
  • Updating setuptools (65.6.3 -> 67.6.0)
  • Installing six (1.16.0)
  • Installing blinker (1.5)
  • Installing distlib (0.3.6)
  • Installing docutils (0.19)
  • Installing feedgenerator (2.0.0)
  • Installing filelock (3.10.0)
  • Installing jinja2 (3.0.3)
  • Installing markdown (3.2)
  • Installing platformdirs (3.1.1)
  • Installing pygments (2.14.0)
  • Installing python-dateutil (2.8.2)
  • Installing pyyaml (6.0)
  • Installing unidecode (1.3.6)
  • Installing cfgv (3.3.1)
  • Installing identify (2.5.21)
  • Installing nodeenv (1.7.0)
  • Installing pelican (4.5.0)
  • Installing pymdown-extensions (9.10)
  • Installing toml (0.10.2)
  • Installing virtualenv (20.21.0)
  • Installing jinja-markdown (1.210911)
  • Installing pelican-jinja2content (1.0.1)
  • Installing pelican-related-posts (1.0.0)
  • Installing pre-commit (2.16.0)
(site-community) site-community/ humitos/poetry-dependencies* 💀  echo $?
0
```

**Comment by agjohnson** [comment]
I thought it might be the Poetry version, but even with 1.4.1 I get the same success. :thinking:

**Pull request merged**
